import { ModelProviderCard } from '@/types/llm';

// ref: https://fireworks.ai/models?show=Serverless
// ref: https://fireworks.ai/pricing
const FireworksAI: ModelProviderCard = {
  chatModels: [
    {
      contextWindowTokens: 131_072,
      description: '',
      displayName: 'Llama 3.3 70B Instruct',
      enabled: true,
      id: 'accounts/fireworks/models/llama-v3p3-70b-instruct',
    },
    {
      contextWindowTokens: 131_072,
      description: '',
      displayName: 'Llama 3.2 3B Instruct',
      enabled: true,
      id: 'accounts/fireworks/models/llama-v3p2-3b-instruct',
    },
    {
      contextWindowTokens: 131_072,
      description: '',
      displayName: 'Llama 3.2 11B Vision Instruct',
      enabled: true,
      id: 'accounts/fireworks/models/llama-v3p2-11b-vision-instruct',
      vision: true,
    },
    {
      contextWindowTokens: 131_072,
      description: '',
      displayName: 'Llama 3.2 90B Vision Instruct',
      enabled: true,
      id: 'accounts/fireworks/models/llama-v3p2-90b-vision-instruct',
      vision: true,
    },
    {
      contextWindowTokens: 131_072,
      description: '',
      displayName: 'Llama 3.1 8B Instruct',
      id: 'accounts/fireworks/models/llama-v3p1-8b-instruct',
    },
    {
      contextWindowTokens: 131_072,
      description: '',
      displayName: 'Llama 3.1 70B Instruct',
      functionCall: true,
      id: 'accounts/fireworks/models/llama-v3p1-70b-instruct',
    },
    {
      contextWindowTokens: 131_072,
      description: '',
      displayName: 'Llama 3.1 405B Instruct',
      functionCall: true,
      id: 'accounts/fireworks/models/llama-v3p1-405b-instruct',
    },
    {
      contextWindowTokens: 8192,
      description: '',
      displayName: 'Llama 3 8B Instruct',
      id: 'accounts/fireworks/models/llama-v3-8b-instruct',
    },
    {
      contextWindowTokens: 8192,
      description: '',
      displayName: 'Llama 3 70B Instruct',
      id: 'accounts/fireworks/models/llama-v3-70b-instruct',
    },
    {
      contextWindowTokens: 8192,
      description: '',
      displayName: 'Llama 3 8B Instruct (HF version)',
      id: 'accounts/fireworks/models/llama-v3-8b-instruct-hf',
    },
    {
      contextWindowTokens: 32_768,
      description: '',
      displayName: 'Mistral Small 3 Instruct',
      enabled: true,
      id: 'accounts/fireworks/models/mistral-small-24b-instruct-2501',
    },
    {
      contextWindowTokens: 32_768,
      description: '',
      displayName: 'Mixtral MoE 8x7B Instruct',
      id: 'accounts/fireworks/models/mixtral-8x7b-instruct',
    },
    {
      contextWindowTokens: 65_536,
      description: '',
      displayName: 'Mixtral MoE 8x22B Instruct',
      functionCall: true,
      id: 'accounts/fireworks/models/mixtral-8x22b-instruct',
    },
    {
      contextWindowTokens: 32_064,
      description: '',
      displayName: 'Phi 3.5 Vision Instruct',
      enabled: true,
      id: 'accounts/fireworks/models/phi-3-vision-128k-instruct',
      vision: true,
    },
    {
      contextWindowTokens: 32_768,
      description: '',
      displayName: 'MythoMax L2 13b',
      id: 'accounts/fireworks/models/mythomax-l2-13b',
    },
    {
      contextWindowTokens: 131_072,
      description: '',
      displayName: 'Deepseek V3',
      enabled: true,
      id: 'accounts/fireworks/models/deepseek-v3',
    },
    {
      contextWindowTokens: 163_840,
      description: '',
      displayName: 'Deepseek R1',
      enabled: true,
      id: 'accounts/fireworks/models/deepseek-r1',
    },
    {
      contextWindowTokens: 32_768,
      description: '',
      displayName: 'Qwen Qwq 32b Preview',
      enabled: true,
      id: 'accounts/fireworks/models/qwen-qwq-32b-preview',
    },
    {
      contextWindowTokens: 32_768,
      description: '',
      displayName: 'Qwen2.5 72B Instruct',
      enabled: true,
      id: 'accounts/fireworks/models/qwen2p5-72b-instruct',
    },
    {
      contextWindowTokens: 32_768,
      description: '',
      displayName: 'Qwen2 VL 72B Instruct',
      enabled: true,
      id: 'accounts/fireworks/models/qwen2-vl-72b-instruct',
      vision: true,
    },
    {
      contextWindowTokens: 32_768,
      description: '',
      displayName: 'Qwen2.5-Coder-32B-Instruct',
      enabled: true,
      id: 'accounts/fireworks/models/qwen2p5-coder-32b-instruct',
    },
    {
      contextWindowTokens: 32_768,
      description: '',
      displayName: 'Yi-Large',
      enabled: true,
      id: 'accounts/yi-01-ai/models/yi-large',
    },
  ],
  checkModel: 'accounts/fireworks/models/llama-v3p2-3b-instruct',
  description: '',
  id: 'fireworksai',
  modelList: { showModelFetcher: true },
  modelsUrl: 'https://fireworks.ai/models?show=Serverless',
  name: 'Fireworks AI',
  settings: {
    proxyUrl: {
      placeholder: 'https://api.fireworks.ai/inference/v1',
    },
    sdkType: 'openai',
    showModelFetcher: true,
  },
  url: 'https://fireworks.ai',
};

export default FireworksAI;
