import { ModelProviderCard } from '@/types/llm';

// ref: https://github.com/marketplace/models
const Github: ModelProviderCard = {
  chatModels: [
    {
      contextWindowTokens: 200_000,
      description: '',
      displayName: 'OpenAI o1',
      enabled: true,
      functionCall: false,
      id: 'o1',
      maxOutput: 100_000,
      vision: true,
    },
    {
      contextWindowTokens: 128_000,
      description: '',
      displayName: 'OpenAI o1-mini',
      enabled: true,
      functionCall: false,
      id: 'o1-mini',
      maxOutput: 65_536,
      vision: true,
    },
    {
      contextWindowTokens: 128_000,
      description: '',
      displayName: 'OpenAI o1-preview',
      enabled: true,
      functionCall: false,
      id: 'o1-preview',
      maxOutput: 32_768,
      vision: true,
    },
    {
      contextWindowTokens: 134_144,
      description: '',
      displayName: 'OpenAI GPT-4o mini',
      enabled: true,
      functionCall: true,
      id: 'gpt-4o-mini',
      maxOutput: 4096,
      vision: true,
    },
    {
      contextWindowTokens: 134_144,
      description: '',
      displayName: 'OpenAI GPT-4o',
      enabled: true,
      functionCall: true,
      id: 'gpt-4o',
      maxOutput: 16_384,
      vision: true,
    },
    {
      contextWindowTokens: 128_000,
      displayName: 'DeepSeek R1',
      id: 'DeepSeek-R1',
      maxOutput: 4096,
    },
    {
      contextWindowTokens: 262_144,
      description: '',
      displayName: 'AI21 Jamba 1.5 Mini',
      functionCall: true,
      id: 'ai21-jamba-1.5-mini',
      maxOutput: 4096,
    },
    {
      contextWindowTokens: 262_144,
      description: '',
      displayName: 'AI21 Jamba 1.5 Large',
      functionCall: true,
      id: 'ai21-jamba-1.5-large',
      maxOutput: 4096,
    },
    {
      contextWindowTokens: 131_072,
      description: '',
      displayName: 'Cohere Command R',
      id: 'cohere-command-r',
      maxOutput: 4096,
    },
    {
      contextWindowTokens: 131_072,
      description: '',
      displayName: 'Cohere Command R+',
      id: 'cohere-command-r-plus',
      maxOutput: 4096,
    },
    {
      contextWindowTokens: 131_072,
      description: '',
      displayName: 'Mistral Nemo',
      id: 'mistral-nemo',
      maxOutput: 4096,
    },
    {
      contextWindowTokens: 131_072,
      description: '',
      displayName: 'Mistral Small',
      id: 'mistral-small',
      maxOutput: 4096,
    },
    {
      contextWindowTokens: 131_072,
      description: '',
      displayName: 'Mistral Large',
      id: 'mistral-large',
      maxOutput: 4096,
    },
    {
      contextWindowTokens: 262_144,
      displayName: 'Codestral',
      id: 'Codestral-2501',
      maxOutput: 4096,
    },
    {
      contextWindowTokens: 131_072,
      description: '',
      displayName: 'Llama 3.2 11B Vision',
      id: 'llama-3.2-11b-vision-instruct',
      maxOutput: 4096,
      vision: true,
    },
    {
      contextWindowTokens: 131_072,
      description: '',
      displayName: 'Llama 3.2 90B Vision',
      id: 'llama-3.2-90b-vision-instruct',
      maxOutput: 4096,
      vision: true,
    },
    {
      contextWindowTokens: 32_768,
      description: '',
      displayName: 'Llama 3.3 70B Instruct',
      enabled: true,
      functionCall: true,
      id: 'llama-3.3-70b-instruct',
    },
    {
      contextWindowTokens: 131_072,
      description: '',
      displayName: 'Meta Llama 3.1 8B',
      id: 'meta-llama-3.1-8b-instruct',
      maxOutput: 4096,
    },
    {
      contextWindowTokens: 131_072,
      description: '',
      displayName: 'Meta Llama 3.1 70B',
      id: 'meta-llama-3.1-70b-instruct',
      maxOutput: 4096,
    },
    {
      contextWindowTokens: 131_072,
      description: '',
      displayName: 'Meta Llama 3.1 405B',
      id: 'meta-llama-3.1-405b-instruct',
      maxOutput: 4096,
    },
    {
      contextWindowTokens: 8192,
      description: '',
      displayName: 'Meta Llama 3 8B',
      id: 'meta-llama-3-8b-instruct',
      maxOutput: 4096,
    },
    {
      contextWindowTokens: 8192,
      description: '',
      displayName: 'Meta Llama 3 70B',
      id: 'meta-llama-3-70b-instruct',
      maxOutput: 4096,
    },
    {
      contextWindowTokens: 16_384,
      displayName: 'Phi 4',
      id: 'Phi-4',
      maxOutput: 16_384,
    },
    {
      contextWindowTokens: 131_072,
      displayName: 'Phi 3.5 MoE',
      id: 'Phi-3.5-MoE-instruct',
      maxOutput: 4096,
    },
    {
      contextWindowTokens: 131_072,
      description: '',
      displayName: 'Phi-3.5-mini 128K',
      id: 'Phi-3.5-mini-instruct',
      maxOutput: 4096,
    },
    {
      contextWindowTokens: 131_072,
      description: '',
      displayName: 'Phi-3.5-vision 128K',
      id: 'Phi-3.5-vision-instrust',
      maxOutput: 4096,
      vision: true,
    },
    {
      contextWindowTokens: 4096,
      description: '',
      displayName: 'Phi-3-mini 4K',
      id: 'Phi-3-mini-4k-instruct',
      maxOutput: 4096,
    },
    {
      contextWindowTokens: 131_072,
      description: '',
      displayName: 'Phi-3-mini 128K',
      id: 'Phi-3-mini-128k-instruct',
      maxOutput: 4096,
    },
    {
      contextWindowTokens: 8192,
      description: '',
      displayName: 'Phi-3-small 8K',
      id: 'Phi-3-small-8k-instruct',
      maxOutput: 4096,
    },
    {
      contextWindowTokens: 131_072,
      description: '',
      displayName: 'Phi-3-small 128K',
      id: 'Phi-3-small-128k-instruct',
      maxOutput: 4096,
    },
    {
      contextWindowTokens: 4096,
      description: '',
      displayName: 'Phi-3-medium 4K',
      id: 'Phi-3-medium-4k-instruct',
      maxOutput: 4096,
    },
    {
      contextWindowTokens: 131_072,
      description: '',
      displayName: 'Phi-3-medium 128K',
      id: 'Phi-3-medium-128k-instruct',
      maxOutput: 4096,
    },
  ],
  checkModel: 'microsoft/Phi-3-mini-4k-instruct',
  // Ref: https://github.blog/news-insights/product-news/introducing-github-models/
  description: '',
  id: 'github',
  modelList: { showModelFetcher: true },
  // I'm not sure if it is good to show the model fetcher, as remote list is not complete.
  name: 'GitHub',
  settings: {
    sdkType: 'azure',
    showModelFetcher: true,
  },
  url: 'https://github.com/marketplace/models',
};

export default Github;
