import { ModelProviderCard } from '@/types/llm';

const Higress: ModelProviderCard = {
  chatModels: [
    //qwen
    {
      contextWindowTokens: 131_072,
      description: '',
      displayName: 'Qwen Turbo',
      enabled: true,
      functionCall: true,
      id: 'qwen-turbo',
    },
    {
      contextWindowTokens: 131_072,
      description: '',
      displayName: 'Qwen Plus',
      enabled: true,
      functionCall: true,
      id: 'qwen-plus',
    },
    {
      contextWindowTokens: 32_768,
      description: '',
      displayName: 'Qwen Max',
      enabled: true,
      functionCall: true,
      id: 'qwen-max',
    },
    {
      contextWindowTokens: 1_000_000,
      description: '',
      displayName: 'Qwen Long',
      id: 'qwen-long',
    },
    //后面几个qwen未知支持
    {
      contextWindowTokens: 32_000,
      description: '',
      displayName: 'Qwen VL Plus',
      enabled: true,
      id: 'qwen-vl-plus-latest',
      vision: true,
    },
    {
      contextWindowTokens: 32_000,
      description: '',
      displayName: 'Qwen VL Max',
      enabled: true,
      id: 'qwen-vl-max-latest',
      vision: true,
    },
    {
      contextWindowTokens: 4096,
      description: '',
      displayName: 'Qwen Math Turbo',
      id: 'qwen-math-turbo-latest',
    },
    {
      contextWindowTokens: 4096,
      description: '',
      displayName: 'Qwen Math Plus',
      id: 'qwen-math-plus-latest',
    },
    {
      contextWindowTokens: 131_072,
      description: '',
      displayName: 'Qwen Coder Turbo',
      id: 'qwen-coder-turbo-latest',
    },
    {
      contextWindowTokens: 131_072,
      description: '',
      displayName: 'Qwen2.5 7B',
      functionCall: true,
      id: 'qwen2.5-7b-instruct',
    },
    {
      contextWindowTokens: 131_072,
      description: '',
      displayName: 'Qwen2.5 14B',
      functionCall: true,
      id: 'qwen2.5-14b-instruct',
    },
    {
      contextWindowTokens: 131_072,
      description: '',
      displayName: 'Qwen2.5 32B',
      functionCall: true,
      id: 'qwen2.5-32b-instruct',
    },
    {
      contextWindowTokens: 131_072,
      description: '',
      displayName: 'Qwen2.5 72B',
      functionCall: true,
      id: 'qwen2.5-72b-instruct',
    },
    {
      contextWindowTokens: 4096,
      description: '',
      displayName: 'Qwen2.5 Math 1.5B',
      id: 'qwen2.5-math-1.5b-instruct',
    },
    {
      contextWindowTokens: 4096,
      description: '',
      displayName: 'Qwen2.5 Math 7B',
      id: 'qwen2.5-math-7b-instruct',
    },
    {
      contextWindowTokens: 4096,
      description: '',
      displayName: 'Qwen2.5 Math 72B',
      id: 'qwen2.5-math-72b-instruct',
    },
    {
      contextWindowTokens: 131_072,
      description: '',
      displayName: 'Qwen2.5 Coder 1.5B',
      id: 'qwen2.5-coder-1.5b-instruct',
    },
    {
      contextWindowTokens: 131_072,
      description: '',
      displayName: 'Qwen2.5 Coder 7B',
      id: 'qwen2.5-coder-7b-instruct',
    },
    {
      contextWindowTokens: 8000,
      description: '',
      displayName: 'Qwen VL',
      id: 'qwen-vl-v1',
      vision: true,
    },
    {
      contextWindowTokens: 8000,
      description: '',
      displayName: 'Qwen VL Chat',
      id: 'qwen-vl-chat-v1',
      vision: true,
    },

    //moonshot
    {
      contextWindowTokens: 8192,
      description: '',
      displayName: 'Moonshot V1 8K',
      enabled: true,
      functionCall: true,
      id: 'moonshot-v1-8k',
    },
    {
      contextWindowTokens: 32_768,
      description: '',
      displayName: 'Moonshot V1 32K',
      enabled: true,
      functionCall: true,
      id: 'moonshot-v1-32k',
    },
    {
      contextWindowTokens: 128_000,
      description: '',
      displayName: 'Moonshot V1 128K',
      enabled: true,
      functionCall: true,
      id: 'moonshot-v1-128k',
    },
    //百川智能
    {
      contextWindowTokens: 32_768,
      description: '',
      displayName: 'Baichuan 4',
      enabled: true,
      functionCall: true,
      id: 'Baichuan4',
      maxOutput: 4096,
    },
    {
      description: '',
      displayName: 'Baichuan 4 Turbo',
      enabled: true,
      functionCall: true,
      id: 'Baichuan4-Turbo',
      // maxOutput: 4096,
    },
    {
      contextWindowTokens: 128_000,
      description: '',
      displayName: 'Baichuan 3 Turbo 128k',
      enabled: true,
      id: 'Baichuan3-Turbo-128k',
      maxOutput: 4096,
    },
    {
      contextWindowTokens: 32_768,
      description: '',
      displayName: 'Baichuan 2 Turbo',
      id: 'Baichuan2-Turbo',
      maxOutput: 8192,
    },
    //零一万物
    {
      contextWindowTokens: 16_384,
      description: '',
      displayName: 'Yi Lightning',
      enabled: true,
      id: 'yi-lightning',
    },
    {
      contextWindowTokens: 16_384,
      description: '',
      displayName: 'Yi Spark',
      enabled: true,
      id: 'yi-spark',
    },
    {
      contextWindowTokens: 16_384,
      description: '',
      displayName: 'Yi Medium',
      enabled: true,
      id: 'yi-medium',
    },
    {
      contextWindowTokens: 200_000,
      description: '',
      displayName: 'Yi Medium 200K',
      enabled: true,
      id: 'yi-medium-200k',
    },
    {
      contextWindowTokens: 16_384,
      description: '',
      displayName: 'Yi Large Turbo',
      enabled: true,
      id: 'yi-large-turbo',
    },
    {
      contextWindowTokens: 16_384,
      description: '',
      displayName: 'Yi Large RAG',
      enabled: true,
      id: 'yi-large-rag',
    },
    {
      contextWindowTokens: 32_768,
      description: '',
      displayName: 'Yi Large FC',
      enabled: true,
      functionCall: true,
      id: 'yi-large-fc',
    },
    {
      contextWindowTokens: 32_768,
      description: '',
      displayName: 'Yi Large',
      id: 'yi-large',
    },
    {
      contextWindowTokens: 16_384,
      description: '',
      displayName: 'Yi Vision',
      enabled: true,
      id: 'yi-vision',
      vision: true,
    },
    {
      contextWindowTokens: 16_384,
      description: '',
      displayName: 'Yi Large Preview',
      id: 'yi-large-preview',
    },
    {
      contextWindowTokens: 16_384,
      description: '',
      displayName: 'Yi Lightning Lite',
      id: 'yi-lightning-lite',
    },
    //智谱AI
    {
      contextWindowTokens: 128_000,
      description: '',
      displayName: 'GLM-4-Flash',
      enabled: true,
      functionCall: true,
      id: 'glm-4-flash',
    },
    {
      contextWindowTokens: 128_000,
      description: '',
      displayName: 'GLM-4-FlashX',
      enabled: true,
      functionCall: true,
      id: 'glm-4-flashx',
    },
    {
      contextWindowTokens: 1_024_000,
      description: '',
      displayName: 'GLM-4-Long',
      functionCall: true,
      id: 'glm-4-long',
    },
    {
      contextWindowTokens: 128_000,
      description: '',
      displayName: 'GLM-4-Air',
      enabled: true,
      functionCall: true,
      id: 'glm-4-air',
    },
    {
      contextWindowTokens: 8192,
      description: '',
      displayName: 'GLM-4-AirX',
      enabled: true,
      functionCall: true,
      id: 'glm-4-airx',
    },
    {
      contextWindowTokens: 128_000,
      description: '',
      displayName: 'GLM-4-AllTools',
      functionCall: true,
      id: 'glm-4-alltools',
    },
    {
      contextWindowTokens: 128_000,
      description: '',
      displayName: 'GLM-4-Plus',
      enabled: true,
      functionCall: true,
      id: 'glm-4-plus',
    },
    {
      contextWindowTokens: 128_000,
      description: '',
      displayName: 'GLM-4-0520',
      functionCall: true,
      id: 'glm-4-0520',
    },
    {
      contextWindowTokens: 128_000,
      description: '',
      displayName: 'GLM-4',
      functionCall: true,
      id: 'glm-4',
    },
    {
      contextWindowTokens: 8192,
      description: '',
      displayName: 'GLM-4V-Plus',
      enabled: true,
      id: 'glm-4v-plus',
      vision: true,
    },
    {
      contextWindowTokens: 2048,
      description: '',
      displayName: 'GLM-4V',
      id: 'glm-4v',
      vision: true,
    },
    {
      contextWindowTokens: 4096,
      description: '',
      displayName: 'CharGLM-3',
      id: 'charglm-3',
    },
    {
      contextWindowTokens: 8192,
      description: '',
      displayName: 'Emohaa',
      id: 'emohaa',
    },
    //360智脑
    {
      contextWindowTokens: 8192,
      description: '',
      displayName: '360GPT2 Pro',
      enabled: true,
      id: '360gpt2-pro',
      maxOutput: 7000,
    },
    {
      contextWindowTokens: 8192,
      description: '',
      displayName: '360GPT Pro',
      enabled: true,
      functionCall: true,
      id: '360gpt-pro',
      maxOutput: 7000,
    },
    {
      contextWindowTokens: 8192,
      description: '',
      displayName: '360GPT Turbo',
      enabled: true,
      id: '360gpt-turbo',
      maxOutput: 7000,
    },
    {
      contextWindowTokens: 8192,
      description: '',
      displayName: '360GPT Turbo Responsibility 8K',
      enabled: true,
      id: '360gpt-turbo-responsibility-8k',
      maxOutput: 2048,
    },
    //文心一言
    {
      contextWindowTokens: 8192,
      description: '',
      displayName: 'ERNIE 3.5 8K',
      enabled: true,
      id: 'ERNIE-3.5-8K',
    },
    {
      contextWindowTokens: 8192,
      description: '',
      displayName: 'ERNIE 3.5 8K Preview',
      id: 'ERNIE-3.5-8K-Preview',
    },
    {
      contextWindowTokens: 128_000,
      description: '',
      displayName: 'ERNIE 3.5 128K',
      enabled: true,
      id: 'ERNIE-3.5-128K',
    },
    {
      contextWindowTokens: 8192,
      description: '',
      displayName: 'ERNIE 4.0 8K',
      enabled: true,
      id: 'ERNIE-4.0-8K-Latest',
    },
    {
      contextWindowTokens: 8192,
      description: '',
      displayName: 'ERNIE 4.0 8K Preview',
      id: 'ERNIE-4.0-8K-Preview',
    },
    {
      contextWindowTokens: 8192,
      description: '',
      displayName: 'ERNIE 4.0 Turbo 8K',
      enabled: true,
      id: 'ERNIE-4.0-Turbo-8K-Latest',
    },
    {
      contextWindowTokens: 8192,
      description: '',
      displayName: 'ERNIE 4.0 Turbo 8K Preview',
      id: 'ERNIE-4.0-Turbo-8K-Preview',
    },
    {
      contextWindowTokens: 128_000,
      description: '',
      displayName: 'ERNIE Lite Pro 128K',
      enabled: true,
      id: 'ERNIE-Lite-Pro-128K',
    },
    {
      contextWindowTokens: 128_000,
      description: '',
      displayName: 'ERNIE Speed Pro 128K',
      enabled: true,
      id: 'ERNIE-Speed-Pro-128K',
    },
    {
      contextWindowTokens: 128_000,
      description: '',
      displayName: 'ERNIE Speed 128K',
      id: 'ERNIE-Speed-128K',
    },
    {
      contextWindowTokens: 8192,
      description: '',
      displayName: 'ERNIE Character 8K',
      id: 'ERNIE-Character-8K',
    },
    //混元
    {
      contextWindowTokens: 256_000,
      description: '',
      displayName: 'Hunyuan Lite',
      enabled: true,
      id: 'hunyuan-lite',
      maxOutput: 6000,
    },
    {
      contextWindowTokens: 32_000,
      description: '',
      displayName: 'Hunyuan Standard',
      enabled: true,
      id: 'hunyuan-standard',
      maxOutput: 2000,
    },
    {
      contextWindowTokens: 256_000,
      description: '',
      displayName: 'Hunyuan Standard 256K',
      enabled: true,
      id: 'hunyuan-standard-256K',
      maxOutput: 6000,
    },
    {
      contextWindowTokens: 32_000,
      description: '',
      displayName: 'Hunyuan Turbo',
      enabled: true,
      functionCall: true,
      id: 'hunyuan-turbo',
      maxOutput: 4000,
    },
    {
      contextWindowTokens: 32_000,
      description: '',
      displayName: 'Hunyuan Pro',
      enabled: true,
      functionCall: true,
      id: 'hunyuan-pro',
      maxOutput: 4000,
    },
    {
      description: '',
      displayName: 'Hunyuan Large',
      enabled: true,
      functionCall: true,
      id: 'hunyuan-large',
      // maxOutput: 4000,
      vision: true,
    },
    {
      contextWindowTokens: 8000,
      description: '',
      displayName: 'Hunyuan Code',
      id: 'hunyuan-code',
      maxOutput: 4000,
    },
    {
      contextWindowTokens: 32_000,
      description: '',
      displayName: 'Hunyuan FunctionCall',
      functionCall: true,
      id: 'hunyuan-functioncall',
      maxOutput: 4000,
    },
    {
      contextWindowTokens: 8000,
      description: '',
      displayName: 'Hunyuan Role',
      id: 'hunyuan-role',
      maxOutput: 4000,
    },
    //阶跃星辰
    {
      contextWindowTokens: 8000,
      description: '',
      displayName: 'Step 1 Flash',
      enabled: true,
      functionCall: true,
      id: 'step-1-flash',
    },
    {
      contextWindowTokens: 8000,
      description: '',
      displayName: 'Step 1 8K',
      enabled: true,
      functionCall: true,
      id: 'step-1-8k',
    },
    {
      contextWindowTokens: 32_000,
      description: '',
      displayName: 'Step 1 32K',
      enabled: true,
      functionCall: true,
      id: 'step-1-32k',
    },
    {
      contextWindowTokens: 128_000,
      description: '',
      displayName: 'Step 1 128K',
      enabled: true,
      functionCall: true,
      id: 'step-1-128k',
    },
    {
      contextWindowTokens: 256_000,
      description: '',
      displayName: 'Step 1 256K',
      functionCall: true,
      id: 'step-1-256k',
    },
    {
      contextWindowTokens: 16_000,
      description: '',
      displayName: 'Step 2 16K',
      enabled: true,
      functionCall: true,
      id: 'step-2-16k',
    },
    {
      contextWindowTokens: 8000,
      description: '',
      displayName: 'Step 1V 8K',
      enabled: true,
      functionCall: true,
      id: 'step-1v-8k',
      vision: true,
    },
    {
      contextWindowTokens: 32_000,
      description: '',
      displayName: 'Step 1V 32K',
      enabled: true,
      functionCall: true,
      id: 'step-1v-32k',
      vision: true,
    },
    {
      contextWindowTokens: 32_000,
      description: '',
      displayName: 'Step 1.5V Mini',
      enabled: true,
      id: 'step-1.5v-mini',
      vision: true,
    },
    {
      contextWindowTokens: 8192,
      description: '',
      displayName: 'Spark Lite',
      enabled: true,
      functionCall: false,
      id: 'lite',
      maxOutput: 4096,
    },
    {
      contextWindowTokens: 8192,
      description: '',
      displayName: 'Spark Pro',
      enabled: true,
      functionCall: false,
      id: 'generalv3',
      maxOutput: 8192,
    },
    {
      contextWindowTokens: 131_072,
      description: '',
      displayName: 'Spark Pro 128K',
      enabled: true,
      functionCall: false,
      id: 'pro-128k',
      maxOutput: 4096,
    },
    {
      contextWindowTokens: 8192,
      description: '',
      displayName: 'Spark Max',
      enabled: true,
      functionCall: false,
      id: 'generalv3.5',
      maxOutput: 8192,
    },
    {
      contextWindowTokens: 32_768,
      description: '',
      displayName: 'Spark Max 32K',
      enabled: true,
      functionCall: false,
      id: 'max-32k',
      maxOutput: 8192,
    },
    {
      contextWindowTokens: 8192,
      description: '',
      displayName: 'Spark 4.0 Ultra',
      enabled: true,
      functionCall: false,
      id: '4.0Ultra',
      maxOutput: 8192,
    },
    //openai
    {
      contextWindowTokens: 128_000,
      description: '',
      displayName: 'OpenAI o1-mini',
      enabled: true,
      id: 'o1-mini',
      maxOutput: 65_536,
      releasedAt: '2024-09-12',
    },
    {
      contextWindowTokens: 128_000,
      description: '',
      displayName: 'OpenAI o1-preview',
      enabled: true,
      id: 'o1-preview',
      maxOutput: 32_768,
      releasedAt: '2024-09-12',
    },
    {
      contextWindowTokens: 128_000,
      description: '',
      displayName: 'GPT-4o mini',
      enabled: true,
      functionCall: true,
      id: 'gpt-4o-mini',
      maxOutput: 16_385,
      vision: true,
    },
    {
      contextWindowTokens: 128_000,
      description: '',
      displayName: 'GPT-4o',
      enabled: true,
      functionCall: true,
      id: 'gpt-4o',
      vision: true,
    },
    {
      contextWindowTokens: 128_000,
      description: '',
      displayName: 'GPT-4o 0806',
      functionCall: true,
      id: 'gpt-4o-2024-08-06',
      vision: true,
    },
    {
      contextWindowTokens: 128_000,
      description: '',
      displayName: 'GPT-4o 0513',
      functionCall: true,
      id: 'gpt-4o-2024-05-13',
      vision: true,
    },
    {
      contextWindowTokens: 128_000,
      description: '',
      displayName: 'ChatGPT-4o',
      enabled: true,
      id: 'chatgpt-4o-latest',
      vision: true,
    },
    {
      contextWindowTokens: 128_000,
      description: '',
      displayName: 'GPT-4 Turbo',
      functionCall: true,
      id: 'gpt-4-turbo',
      vision: true,
    },
    {
      contextWindowTokens: 128_000,
      description: '',
      displayName: 'GPT-4 Turbo Vision 0409',
      functionCall: true,
      id: 'gpt-4-turbo-2024-04-09',
      vision: true,
    },
    {
      contextWindowTokens: 128_000,
      description: '',
      displayName: 'GPT-4 Turbo Preview',
      functionCall: true,
      id: 'gpt-4-turbo-preview',
    },
    {
      contextWindowTokens: 128_000,
      description: '',
      displayName: 'GPT-4 Turbo Preview 0125',
      functionCall: true,
      id: 'gpt-4-0125-preview',
    },
    {
      contextWindowTokens: 128_000,
      description: '',
      displayName: 'GPT-4 Turbo Preview 1106',
      functionCall: true,
      id: 'gpt-4-1106-preview',
    },
    {
      contextWindowTokens: 8192,
      description: '',
      displayName: 'GPT-4',
      functionCall: true,
      id: 'gpt-4',
    },
    {
      contextWindowTokens: 8192,
      description: '',
      displayName: 'GPT-4 0613',
      functionCall: true,
      id: 'gpt-4-0613',
    },
    {
      contextWindowTokens: 32_768,
      description: '',
      // Will be discontinued on June 6, 2025
      displayName: 'GPT-4 32K',
      functionCall: true,
      id: 'gpt-4-32k',
    },
    {
      contextWindowTokens: 32_768,
      // Will be discontinued on June 6, 2025
      description: '',
      displayName: 'GPT-4 32K 0613',
      functionCall: true,
      id: 'gpt-4-32k-0613',
    },
    {
      contextWindowTokens: 16_385,
      description: '',
      displayName: 'GPT-3.5 Turbo',
      functionCall: true,
      id: 'gpt-3.5-turbo',
    },
    {
      contextWindowTokens: 16_385,
      description: '',
      displayName: 'GPT-3.5 Turbo 0125',
      functionCall: true,
      id: 'gpt-3.5-turbo-0125',
    },
    {
      contextWindowTokens: 16_385,
      description: '',
      displayName: 'GPT-3.5 Turbo 1106',
      functionCall: true,
      id: 'gpt-3.5-turbo-1106',
    },
    {
      contextWindowTokens: 4096,
      description: '',
      displayName: 'GPT-3.5 Turbo Instruct',
      id: 'gpt-3.5-turbo-instruct',
    },
    //azure
    {
      contextWindowTokens: 16_385,
      deploymentName: 'gpt-35-turbo',
      description: '',
      displayName: 'GPT 3.5 Turbo',
      enabled: true,
      functionCall: true,
      id: 'gpt-35-turbo',
      maxOutput: 4096,
    },
    {
      contextWindowTokens: 16_384,
      deploymentName: 'gpt-35-turbo-16k',
      description: '',
      displayName: 'GPT 3.5 Turbo',
      functionCall: true,
      id: 'gpt-35-turbo-16k',
    },
    {
      contextWindowTokens: 128_000,
      deploymentName: 'gpt-4-turbo',
      description: '',
      displayName: 'GPT 4 Turbo',
      enabled: true,
      functionCall: true,
      id: 'gpt-4',
      vision: true,
    },
    {
      contextWindowTokens: 128_000,
      deploymentName: 'gpt-4-vision',
      description: '',
      displayName: 'GPT 4 Turbo with Vision Preview',
      id: 'gpt-4-vision-preview',
      vision: true,
    },
    {
      contextWindowTokens: 128_000,
      deploymentName: 'gpt-4o-mini',
      description: '',
      displayName: 'GPT 4o Mini',
      enabled: true,
      functionCall: true,
      id: 'gpt-4o-mini',
      vision: true,
    },
    {
      contextWindowTokens: 128_000,
      deploymentName: 'gpt-4o',
      description: '',
      displayName: 'GPT 4o',
      enabled: true,
      functionCall: true,
      id: 'gpt-4o',
      vision: true,
    },
    //github
    {
      contextWindowTokens: 128_000,
      description: '',
      displayName: 'OpenAI o1-mini',
      enabled: true,
      functionCall: false,
      id: 'o1-mini',
      maxOutput: 65_536,
      vision: true,
    },
    {
      contextWindowTokens: 128_000,
      description: '',
      displayName: 'OpenAI o1-preview',
      enabled: true,
      functionCall: false,
      id: 'o1-preview',
      maxOutput: 32_768,
      vision: true,
    },
    {
      contextWindowTokens: 128_000,
      description: '',
      displayName: 'OpenAI GPT-4o mini',
      enabled: true,
      functionCall: true,
      id: 'gpt-4o-mini',
      maxOutput: 4096,
      vision: true,
    },
    {
      contextWindowTokens: 128_000,
      description: '',
      displayName: 'OpenAI GPT-4o',
      enabled: true,
      functionCall: true,
      id: 'gpt-4o',
      maxOutput: 4096,
      vision: true,
    },
    {
      contextWindowTokens: 262_144,
      description: '',
      displayName: 'AI21 Jamba 1.5 Mini',
      functionCall: true,
      id: 'ai21-jamba-1.5-mini',
      maxOutput: 4096,
    },
    {
      contextWindowTokens: 262_144,
      description: '',
      displayName: 'AI21 Jamba 1.5 Large',
      functionCall: true,
      id: 'ai21-jamba-1.5-large',
      maxOutput: 4096,
    },
    {
      contextWindowTokens: 131_072,
      description: '',
      displayName: 'Cohere Command R',
      id: 'cohere-command-r',
      maxOutput: 4096,
    },
    {
      contextWindowTokens: 131_072,
      description: '',
      displayName: 'Cohere Command R+',
      id: 'cohere-command-r-plus',
      maxOutput: 4096,
    },
    {
      contextWindowTokens: 131_072,
      description: '',
      displayName: 'Mistral Nemo',
      id: 'mistral-nemo',
      maxOutput: 4096,
    },
    {
      contextWindowTokens: 131_072,
      description: '',
      displayName: 'Mistral Small',
      id: 'mistral-small',
      maxOutput: 4096,
    },
    {
      contextWindowTokens: 131_072,
      description: '',
      displayName: 'Mistral Large',
      id: 'mistral-large',
      maxOutput: 4096,
    },
    {
      contextWindowTokens: 131_072,
      description: '',
      displayName: 'Llama 3.2 11B Vision',
      id: 'llama-3.2-11b-vision-instruct',
      maxOutput: 4096,
      vision: true,
    },
    {
      contextWindowTokens: 131_072,
      description: '',
      displayName: 'Llama 3.2 90B Vision',
      id: 'llama-3.2-90b-vision-instruct',
      maxOutput: 4096,
      vision: true,
    },
    {
      contextWindowTokens: 131_072,
      description: '',
      displayName: 'Meta Llama 3.1 8B',
      id: 'meta-llama-3.1-8b-instruct',
      maxOutput: 4096,
    },
    {
      contextWindowTokens: 131_072,
      description: '',
      displayName: 'Meta Llama 3.1 70B',
      id: 'meta-llama-3.1-70b-instruct',
      maxOutput: 4096,
    },
    {
      contextWindowTokens: 131_072,
      description: '',
      displayName: 'Meta Llama 3.1 405B',
      id: 'meta-llama-3.1-405b-instruct',
      maxOutput: 4096,
    },
    {
      contextWindowTokens: 8192,
      description: '',
      displayName: 'Meta Llama 3 8B',
      id: 'meta-llama-3-8b-instruct',
      maxOutput: 4096,
    },
    {
      contextWindowTokens: 8192,
      description: '',
      displayName: 'Meta Llama 3 70B',
      id: 'meta-llama-3-70b-instruct',
      maxOutput: 4096,
    },
    {
      contextWindowTokens: 131_072,
      description: '',
      displayName: 'Phi-3.5-mini 128K',
      id: 'Phi-3.5-mini-instruct',
      maxOutput: 4096,
    },
    {
      contextWindowTokens: 131_072,
      description: '',
      displayName: 'Phi-3.5-vision 128K',
      id: 'Phi-3.5-vision-instrust',
      maxOutput: 4096,
      vision: true,
    },
    {
      contextWindowTokens: 4096,
      description: '',
      displayName: 'Phi-3-mini 4K',
      id: 'Phi-3-mini-4k-instruct',
      maxOutput: 4096,
    },
    {
      contextWindowTokens: 131_072,
      description: '',
      displayName: 'Phi-3-mini 128K',
      id: 'Phi-3-mini-128k-instruct',
      maxOutput: 4096,
    },
    {
      contextWindowTokens: 8192,
      description: '',
      displayName: 'Phi-3-small 8K',
      id: 'Phi-3-small-8k-instruct',
      maxOutput: 4096,
    },
    {
      contextWindowTokens: 131_072,
      description: '',
      displayName: 'Phi-3-small 128K',
      id: 'Phi-3-small-128k-instruct',
      maxOutput: 4096,
    },
    {
      contextWindowTokens: 4096,
      description: '',
      displayName: 'Phi-3-medium 4K',
      id: 'Phi-3-medium-4k-instruct',
      maxOutput: 4096,
    },
    {
      contextWindowTokens: 131_072,
      description: '',
      displayName: 'Phi-3-medium 128K',
      id: 'Phi-3-medium-128k-instruct',
      maxOutput: 4096,
    },

    //groq
    {
      contextWindowTokens: 8192,
      description: '',
      displayName: 'Llama 3.2 11B Vision (Preview)',
      enabled: true,
      id: 'llama-3.2-11b-vision-preview',
      maxOutput: 8192,
      vision: true,
    },
    {
      contextWindowTokens: 8192,
      description: '',
      displayName: 'Llama 3.2 90B Vision (Preview)',
      enabled: true,
      id: 'llama-3.2-90b-vision-preview',
      maxOutput: 8192,
      vision: true,
    },
    {
      contextWindowTokens: 131_072,
      description: '',
      displayName: 'Llama 3.1 8B',
      enabled: true,
      functionCall: true,
      id: 'llama-3.1-8b-instant',
      maxOutput: 8192,
    },
    {
      contextWindowTokens: 131_072,
      description: '',
      displayName: 'Llama 3.1 70B',
      enabled: true,
      functionCall: true,
      id: 'llama-3.1-70b-versatile',
      maxOutput: 8192,
    },
    /*
        // Offline due to overwhelming demand! Stay tuned for updates.
        {
          displayName: 'Llama 3.1 405B',
          functionCall: true,
          id: 'llama-3.1-405b-reasoning',
          tokens: 8_192,
        },
    */
    {
      contextWindowTokens: 8192,
      description: '',
      displayName: 'Llama 3 Groq 8B Tool Use (Preview)',
      functionCall: true,
      id: 'llama3-groq-8b-8192-tool-use-preview',
    },
    {
      contextWindowTokens: 8192,
      description: '',
      displayName: 'Llama 3 Groq 70B Tool Use (Preview)',
      functionCall: true,
      id: 'llama3-groq-70b-8192-tool-use-preview',
    },
    {
      contextWindowTokens: 8192,
      description: '',
      displayName: 'Meta Llama 3 8B',
      functionCall: true,
      id: 'llama3-8b-8192',
    },
    {
      contextWindowTokens: 8192,
      description: '',
      displayName: 'Meta Llama 3 70B',
      functionCall: true,
      id: 'llama3-70b-8192',
    },
    {
      contextWindowTokens: 8192,
      description: '',
      displayName: 'Gemma 2 9B',
      enabled: true,
      functionCall: true,
      id: 'gemma2-9b-it',
    },
    {
      contextWindowTokens: 8192,
      description: '',
      displayName: 'Gemma 7B',
      functionCall: true,
      id: 'gemma-7b-it',
    },
    {
      contextWindowTokens: 32_768,
      description: '',
      displayName: 'Mixtral 8x7B',
      functionCall: true,
      id: 'mixtral-8x7b-32768',
    },
    {
      contextWindowTokens: 4096,
      description: '',
      displayName: 'LLaVA 1.5 7B',
      id: 'llava-v1.5-7b-4096-preview',
      vision: true,
    },
    //deepseek
    {
      contextWindowTokens: 128_000,
      description: '',
      displayName: 'DeepSeek V2.5',
      enabled: true,
      functionCall: true,
      id: 'deepseek-chat',
      releasedAt: '2024-09-05',
    },
    //claude
    {
      contextWindowTokens: 200_000,
      description: '',
      displayName: 'Claude 3.5 Haiku',
      enabled: true,
      functionCall: true,
      id: 'claude-3-5-haiku-20241022',
      maxOutput: 8192,
      releasedAt: '2024-11-05',
    },
    {
      contextWindowTokens: 200_000,
      description: '',
      displayName: 'Claude 3.5 Sonnet',
      enabled: true,
      functionCall: true,
      id: 'claude-3-5-sonnet-20241022',
      maxOutput: 8192,
      releasedAt: '2024-10-22',
      vision: true,
    },
    {
      contextWindowTokens: 200_000,
      description: '',
      displayName: 'Claude 3.5 Sonnet 0620',
      functionCall: true,
      id: 'claude-3-5-sonnet-20240620',
      maxOutput: 8192,
      releasedAt: '2024-06-20',
      vision: true,
    },
    {
      contextWindowTokens: 200_000,
      description: '',
      displayName: 'Claude 3 Haiku',
      functionCall: true,
      id: 'claude-3-haiku-20240307',
      maxOutput: 4096,
      releasedAt: '2024-03-07',
      vision: true,
    },
    {
      contextWindowTokens: 200_000,
      description: '',
      displayName: 'Claude 3 Sonnet',
      functionCall: true,
      id: 'claude-3-sonnet-20240229',
      maxOutput: 4096,
      releasedAt: '2024-02-29',
      vision: true,
    },
    {
      contextWindowTokens: 200_000,
      description: '',
      displayName: 'Claude 3 Opus',
      enabled: true,
      functionCall: true,
      id: 'claude-3-opus-20240229',
      maxOutput: 4096,
      releasedAt: '2024-02-29',
      vision: true,
    },
    {
      contextWindowTokens: 200_000,
      description: '',
      displayName: 'Claude 2.1',
      id: 'claude-2.1',
      maxOutput: 4096,
      releasedAt: '2023-11-21',
    },
    {
      contextWindowTokens: 100_000,
      description: '',
      displayName: 'Claude 2.0',
      id: 'claude-2.0',
      maxOutput: 4096,
      releasedAt: '2023-07-11',
    },
    //gemini
    {
      contextWindowTokens: 1_000_000 + 8192,
      description: '',
      displayName: 'Gemini 1.5 Flash',
      enabled: true,
      functionCall: true,
      id: 'gemini-1.5-flash-latest',
      maxOutput: 8192,
      vision: true,
    },
    {
      contextWindowTokens: 1_000_000 + 8192,
      description: '',
      displayName: 'Gemini 1.5 Flash 002',
      enabled: true,
      functionCall: true,
      id: 'gemini-1.5-flash-002',
      maxOutput: 8192,
      releasedAt: '2024-09-25',
      vision: true,
    },
    {
      contextWindowTokens: 1_000_000 + 8192,
      description: '',
      displayName: 'Gemini 1.5 Flash 001',
      functionCall: true,
      id: 'gemini-1.5-flash-001',
      maxOutput: 8192,
      vision: true,
    },
    {
      contextWindowTokens: 1_000_000 + 8192,
      description: '',
      displayName: 'Gemini 1.5 Flash 0827',
      functionCall: true,
      id: 'gemini-1.5-flash-exp-0827',
      maxOutput: 8192,
      releasedAt: '2024-08-27',
      vision: true,
    },
    {
      contextWindowTokens: 1_000_000 + 8192,
      description: '',
      displayName: 'Gemini 1.5 Flash 8B',
      enabled: true,
      functionCall: true,
      id: 'gemini-1.5-flash-8b',
      maxOutput: 8192,
      releasedAt: '2024-10-03',
      vision: true,
    },
    {
      contextWindowTokens: 1_000_000 + 8192,
      description: '',
      displayName: 'Gemini 1.5 Flash 8B 0924',
      functionCall: true,
      id: 'gemini-1.5-flash-8b-exp-0924',
      maxOutput: 8192,
      releasedAt: '2024-09-24',
      vision: true,
    },
    {
      contextWindowTokens: 2_000_000 + 8192,
      description: '',
      displayName: 'Gemini 1.5 Pro',
      enabled: true,
      functionCall: true,
      id: 'gemini-1.5-pro-latest',
      maxOutput: 8192,
      releasedAt: '2024-02-15',
      vision: true,
    },
    {
      contextWindowTokens: 2_000_000 + 8192,
      description: '',
      displayName: 'Gemini 1.5 Pro 002',
      enabled: true,
      functionCall: true,
      id: 'gemini-1.5-pro-002',
      maxOutput: 8192,
      releasedAt: '2024-09-24',
      vision: true,
    },
    {
      contextWindowTokens: 2_000_000 + 8192,
      description: '',
      displayName: 'Gemini 1.5 Pro 001',
      functionCall: true,
      id: 'gemini-1.5-pro-001',
      maxOutput: 8192,
      releasedAt: '2024-02-15',
      vision: true,
    },
    {
      contextWindowTokens: 2_000_000 + 8192,
      description: '',
      displayName: 'Gemini 1.5 Pro 0827',
      functionCall: true,
      id: 'gemini-1.5-pro-exp-0827',
      maxOutput: 8192,
      releasedAt: '2024-08-27',
      vision: true,
    },
    {
      contextWindowTokens: 2_000_000 + 8192,
      description: '',
      displayName: 'Gemini 1.5 Pro 0801',
      functionCall: true,
      id: 'gemini-1.5-pro-exp-0801',
      maxOutput: 8192,
      releasedAt: '2024-08-01',
      vision: true,
    },
    {
      contextWindowTokens: 30_720 + 2048,
      description: '',
      displayName: 'Gemini 1.0 Pro',
      id: 'gemini-1.0-pro-latest',
      maxOutput: 2048,
      releasedAt: '2023-12-06',
    },
    {
      contextWindowTokens: 30_720 + 2048,
      description: '',
      displayName: 'Gemini 1.0 Pro 001 (Tuning)',
      functionCall: true,
      id: 'gemini-1.0-pro-001',
      maxOutput: 2048,
      releasedAt: '2023-12-06',
    },
    {
      contextWindowTokens: 30_720 + 2048,
      description: '',
      displayName: 'Gemini 1.0 Pro 002 (Tuning)',
      id: 'gemini-1.0-pro-002',
      maxOutput: 2048,
      releasedAt: '2023-12-06',
    },
    //mistral

    {
      contextWindowTokens: 128_000,
      description: '',
      displayName: 'Mistral Nemo',
      enabled: true,
      functionCall: true,
      id: 'open-mistral-nemo',
    },
    {
      contextWindowTokens: 128_000,
      description: '',
      displayName: 'Mistral Small',
      enabled: true,
      functionCall: true,
      id: 'mistral-small-latest',
    },
    {
      contextWindowTokens: 128_000,
      description: '',
      displayName: 'Mistral Large',
      enabled: true,
      functionCall: true,
      id: 'mistral-large-latest',
    },
    {
      contextWindowTokens: 32_768,
      description: '',
      displayName: 'Codestral',
      id: 'codestral-latest',
    },
    {
      contextWindowTokens: 128_000,
      description: '',
      displayName: 'Pixtral 12B',
      enabled: true,
      id: 'pixtral-12b-2409',
      vision: true,
    },
    {
      contextWindowTokens: 128_000,
      description: '',
      displayName: 'Ministral 3B',
      id: 'ministral-3b-latest',
    },
    {
      contextWindowTokens: 128_000,
      description: '',
      displayName: 'Ministral 8B',
      id: 'ministral-8b-latest',
    },
    {
      contextWindowTokens: 32_768,
      description: '',
      displayName: 'Mistral 7B',
      id: 'open-mistral-7b',
    },
    {
      contextWindowTokens: 32_768,
      description: '',
      displayName: 'Mixtral 8x7B',
      id: 'open-mixtral-8x7b',
    },
    {
      contextWindowTokens: 65_536,
      description: '',
      displayName: 'Mixtral 8x22B',
      functionCall: true,
      id: 'open-mixtral-8x22b',
    },
    {
      contextWindowTokens: 256_000,
      description: '',
      displayName: 'Codestral Mamba',
      id: 'open-codestral-mamba',
    },
    //minimax
    {
      contextWindowTokens: 245_760,
      description: '',
      displayName: 'abab6.5s',
      enabled: true,
      functionCall: true,
      id: 'abab6.5s-chat',
    },
    {
      contextWindowTokens: 8192,
      description: '',
      displayName: 'abab6.5g',
      enabled: true,
      functionCall: true,
      id: 'abab6.5g-chat',
    },
    {
      contextWindowTokens: 8192,
      description: '',
      displayName: 'abab6.5t',
      enabled: true,
      functionCall: true,
      id: 'abab6.5t-chat',
    },
    {
      contextWindowTokens: 16_384,
      description: '',
      displayName: 'abab5.5',
      id: 'abab5.5-chat',
    },
    {
      contextWindowTokens: 8192,
      description: '',
      displayName: 'abab5.5s',
      id: 'abab5.5s-chat',
    },
    //cohere
    {
      description: '',
      displayName: 'command-r',
      id: 'command-r',
      // tokens: ,
    },
    {
      description: '',
      displayName: 'command-r-plus',
      id: 'command-r-plus',
      // tokens: ,
    },
    {
      description: '',
      displayName: 'command-light',
      id: 'command-light',
      // tokens: ,
    },
    //doubao
    {
      description: '',
      displayName: 'Doubao-lite-4k',
      id: 'Doubao-lite-4k',
      // tokens: ,
    },
    {
      description: '',
      displayName: 'Doubao-lite-32k',
      id: 'Doubao-lite-32k',
      // tokens: ,
    },
    {
      description: '',
      displayName: 'Doubao-lite-128k',
      id: 'Doubao-lite-128k',
      // tokens: ,
    },
    {
      description: '',
      displayName: 'Doubao-pro-4k',
      id: 'Doubao-pro-4k',
      // tokens: ,
    },
    {
      description: '',
      displayName: 'Doubao-pro-32k',
      id: 'Doubao-pro-32k',
      // tokens: ,
    },
    {
      description: '',
      displayName: 'Doubao-pro-128k',
      id: 'Doubao-pro-128k',
      // tokens: ,
    },
    {
      description: '',
      displayName: 'Skylark2-pro-character-4k',
      id: 'Skylark2-pro-character-4k',
      // tokens: ,
    },
    {
      description: '',
      displayName: 'Skylark2-pro-32k',
      id: 'Skylark2-pro-32k',
      // tokens: ,
    },
    {
      description: '',
      displayName: 'Skylark2-pro-4k',
      id: 'Skylark2-pro-4k',
      // tokens: ,
    },
    {
      description: '',
      displayName: 'Skylark2-pro-turbo-8k',
      id: 'Skylark2-pro-turbo-8k',
      // tokens: ,
    },
    {
      description: '',
      displayName: 'Skylark2-lite-8k',
      id: 'Skylark2-lite-8k',
      // tokens: ,
    },
  ],
  checkModel: 'qwen-max',
  description: '',
  id: 'higress',
  modelList: { showModelFetcher: true },
  modelsUrl: 'https://higress.cn/',
  name: 'Higress',
  proxyUrl: {
    desc: '',
    placeholder: 'https://127.0.0.1:8080/v1',
    title: 'AI Gateway地址',
  },
  settings: {
    proxyUrl: {
      desc: '',
      placeholder: 'https://127.0.0.1:8080/v1',
      title: 'AI Gateway地址',
    },
    sdkType: 'openai',
    showModelFetcher: true,
  },
  url: 'https://apig.console.aliyun.com/',
};

export default Higress;
