import { ModelProviderCard } from '@/types/llm';

const Ollama: ModelProviderCard = {
  chatModels: [
    {
      contextWindowTokens: 128_000,
      description: '',
      displayName: 'Llama 3.1 8B',
      enabled: true,
      functionCall: true,
      id: 'llama3.1',
    },
    {
      contextWindowTokens: 128_000,
      description: '',
      displayName: 'Llama 3.1 70B',
      id: 'llama3.1:70b',
    },
    {
      contextWindowTokens: 128_000,
      description: '',
      displayName: 'Llama 3.1 405B',
      id: 'llama3.1:405b',
    },
    {
      contextWindowTokens: 16_384,
      description: '',
      displayName: 'Code Llama 7B',
      enabled: true,
      id: 'codellama',
    },
    {
      contextWindowTokens: 16_384,
      description: '',
      displayName: 'Code Llama 13B',
      id: 'codellama:13b',
    },
    {
      contextWindowTokens: 16_384,
      description: '',
      displayName: 'Code Llama 34B',
      id: 'codellama:34b',
    },
    {
      contextWindowTokens: 16_384,
      description: '',
      displayName: 'Code Llama 70B',
      id: 'codellama:70b',
    },
    {
      contextWindowTokens: 128_000,
      description: '',
      displayName: 'QwQ 32B',
      enabled: true,
      functionCall: true,
      id: 'qwq',
      releasedAt: '2024-11-28',
    },
    {
      contextWindowTokens: 128_000,
      description: '',
      displayName: 'Qwen2.5 0.5B',
      id: 'qwen2.5:0.5b',
    },
    {
      contextWindowTokens: 128_000,
      description: '',
      displayName: 'Qwen2.5 1.5B',
      id: 'qwen2.5:1.5b',
    },
    {
      contextWindowTokens: 128_000,
      description: '',
      displayName: 'Qwen2.5 7B',
      enabled: true,
      functionCall: true,
      id: 'qwen2.5',
    },
    {
      contextWindowTokens: 128_000,
      description: '',
      displayName: 'Qwen2.5 72B',
      id: 'qwen2.5:72b',
    },
    {
      contextWindowTokens: 65_536,
      description: '',
      displayName: 'CodeQwen1.5 7B',
      functionCall: true,
      id: 'codeqwen',
    },
    {
      contextWindowTokens: 128_000,
      description: '',
      displayName: 'Qwen2 0.5B',
      functionCall: true,
      id: 'qwen2:0.5b',
    },
    {
      contextWindowTokens: 128_000,
      description: '',
      displayName: 'Qwen2 1.5B',
      functionCall: true,
      id: 'qwen2:1.5b',
    },
    {
      contextWindowTokens: 128_000,
      description: '',
      displayName: 'Qwen2 7B',
      functionCall: true,
      id: 'qwen2',
    },
    {
      contextWindowTokens: 128_000,
      description: '',
      displayName: 'Qwen2 72B',
      functionCall: true,
      id: 'qwen2:72b',
    },
    {
      contextWindowTokens: 8192,
      description: '',
      displayName: 'Gemma 2 2B',
      id: 'gemma2:2b',
    },
    {
      contextWindowTokens: 8192,
      description: '',
      displayName: 'Gemma 2 9B',
      id: 'gemma2',
    },
    {
      contextWindowTokens: 8192,
      description: '',
      displayName: 'Gemma 2 27B',
      id: 'gemma2:27b',
    },
    {
      contextWindowTokens: 8192,
      description: '',
      displayName: 'CodeGemma 2B',
      id: 'codegemma:2b',
    },
    {
      contextWindowTokens: 8192,
      description: '',
      displayName: 'CodeGemma 7B',
      id: 'codegemma',
    },
    {
      contextWindowTokens: 128_000,
      description: '',
      displayName: 'Phi-3 3.8B',
      enabled: true,
      id: 'phi3',
    },
    {
      contextWindowTokens: 128_000,
      description: '',
      displayName: 'Phi-3 14B',
      id: 'phi3:14b',
    },
    {
      contextWindowTokens: 32_768,
      description: '',
      displayName: 'WizardLM 2 7B',
      enabled: true,
      id: 'wizardlm2',
    },
    {
      contextWindowTokens: 65_536,
      description: '',
      displayName: 'WizardLM 2 8x22B',
      id: 'wizardlm2:8x22b',
    },
    {
      contextWindowTokens: 32_768,
      description: '',
      displayName: 'MathΣtral 7B',
      enabled: true,
      id: 'mathstral',
    },
    {
      contextWindowTokens: 32_768,
      description: '',
      displayName: 'Mistral 7B',
      enabled: true,
      functionCall: true,
      id: 'mistral',
    },
    {
      contextWindowTokens: 32_768,
      description: '',
      displayName: 'Mixtral 8x7B',
      enabled: true,
      functionCall: true,
      id: 'mixtral',
    },
    {
      contextWindowTokens: 65_536,
      description: '',
      displayName: 'Mixtral 8x22B',
      functionCall: true,
      id: 'mixtral:8x22b',
    },
    {
      contextWindowTokens: 128_000,
      description: '',
      displayName: 'Mixtral Large 123B',
      enabled: true,
      id: 'mistral-large',
    },
    {
      contextWindowTokens: 128_000,
      description: '',
      displayName: 'Mixtral Nemo 12B',
      enabled: true,
      functionCall: true,
      id: 'mistral-nemo',
    },
    {
      contextWindowTokens: 32_768,
      description: '',
      displayName: 'Codestral 22B',
      enabled: true,
      id: 'codestral',
    },
    {
      contextWindowTokens: 8192,
      description: '',
      displayName: 'Aya 23 8B',
      enabled: true,
      id: 'aya',
    },
    {
      contextWindowTokens: 8192,
      description: '',
      displayName: 'Aya 23 35B',
      id: 'aya:35b',
    },
    {
      contextWindowTokens: 131_072,
      description: '',
      displayName: 'Command R 35B',
      enabled: true,
      functionCall: true,
      id: 'command-r',
    },
    {
      contextWindowTokens: 131_072,
      description: '',
      displayName: 'Command R+ 104B',
      enabled: true,
      functionCall: true,
      id: 'command-r-plus',
    },
    {
      contextWindowTokens: 32_768,
      description: '',
      displayName: 'DeepSeek V2 16B',
      enabled: true,
      id: 'deepseek-v2',
    },
    {
      contextWindowTokens: 128_000,
      description: '',
      displayName: 'DeepSeek V2 236B',
      id: 'deepseek-v2:236b',
    },
    {
      contextWindowTokens: 128_000,
      description: '',
      displayName: 'DeepSeek Coder V2 16B',
      enabled: true,
      id: 'deepseek-coder-v2',
    },
    {
      contextWindowTokens: 128_000,
      description: '',
      displayName: 'DeepSeek Coder V2 236B',
      id: 'deepseek-coder-v2:236b',
    },
    {
      contextWindowTokens: 4096,
      description: '',
      displayName: 'LLaVA 7B',
      enabled: true,
      id: 'llava',
      vision: true,
    },
    {
      contextWindowTokens: 4096,
      description: '',
      displayName: 'LLaVA 13B',
      id: 'llava:13b',
      vision: true,
    },
    {
      contextWindowTokens: 4096,
      description: '',
      displayName: 'LLaVA 34B',
      id: 'llava:34b',
      vision: true,
    },
    {
      contextWindowTokens: 128_000,
      description: '',
      displayName: 'MiniCPM-V 8B',
      enabled: true,
      id: 'minicpm-v',
      vision: true,
    },
  ],
  checkModel: 'deepseek-r1',
  defaultShowBrowserRequest: true,
  description: '',
  id: 'ollama',
  modelList: { showModelFetcher: true },
  modelsUrl: 'https://ollama.com/library',
  name: 'Ollama',
  settings: {
    defaultShowBrowserRequest: true,
    sdkType: 'ollama',
    showApiKey: false,
    showModelFetcher: true,
  },
  showApiKey: false,
  url: 'https://ollama.com',
};

export default Ollama;
