import { ModelProviderCard } from '@/types/llm';

// ref: https://platform.openai.com/docs/deprecations
const OpenAI: ModelProviderCard = {
  apiKeyUrl: 'https://platform.openai.com/api-keys',
  chatModels: [
    {
      contextWindowTokens: 400_000,
      description: '',
      displayName: 'GPT-5 mini',
      enabled: true,
      functionCall: true,
      id: 'gpt-5-mini',
      maxOutput: 128_000,
      pricing: {
        units: [
          { name: 'textInput', rate: 0.25, strategy: 'fixed', unit: 'millionTokens' },
          { name: 'textOutput', rate: 2, strategy: 'fixed', unit: 'millionTokens' },
          { name: 'textInput_cacheRead', rate: 0.03, strategy: 'fixed', unit: 'millionTokens' },
        ],
      },
      releasedAt: '2025-08-07',
      vision: true,
    },
    {
      contextWindowTokens: 1_047_576,
      description: '',
      displayName: 'GPT-4.1 mini',
      functionCall: true,
      id: 'gpt-4.1-mini',
      maxOutput: 32_768,
      releasedAt: '2025-04-14',
      vision: true,
    },
    {
      contextWindowTokens: 128_000,
      description: '',
      displayName: 'OpenAI o1-mini',
      enabled: true,
      id: 'o1-mini',
      maxOutput: 65_536,
      releasedAt: '2024-09-12',
    },
    {
      contextWindowTokens: 200_000,
      description: '',
      displayName: 'OpenAI o1',
      enabled: true,
      id: 'o1-2024-12-17',
      maxOutput: 100_000,
      releasedAt: '2024-12-17',
      vision: true,
    },
    {
      contextWindowTokens: 128_000,
      description: '',
      displayName: 'OpenAI o1-preview',
      enabled: true,
      id: 'o1-preview',
      maxOutput: 32_768,
      releasedAt: '2024-09-12',
    },
    {
      contextWindowTokens: 128_000,
      description: '',
      displayName: 'GPT-4o mini',
      enabled: true,
      functionCall: true,
      id: 'gpt-4o-mini',
      maxOutput: 16_385,
      vision: true,
    },
    {
      contextWindowTokens: 128_000,
      description: '',
      displayName: 'GPT-4o mini Search Preview',
      functionCall: true,
      id: 'gpt-4o-mini-search-preview',
      maxOutput: 16_384,
      releasedAt: '2024-12-01',
      vision: true,
    },
    {
      contextWindowTokens: 128_000,
      description: '',
      displayName: 'GPT-4o 1120',
      enabled: true,
      functionCall: true,
      id: 'gpt-4o-2024-11-20',
      releasedAt: '2024-11-20',
      vision: true,
    },
    {
      contextWindowTokens: 128_000,
      description: '',
      displayName: 'GPT-4o',
      enabled: true,
      functionCall: true,
      id: 'gpt-4o',
      vision: true,
    },
    {
      contextWindowTokens: 128_000,
      description: '',
      displayName: 'GPT-4o 0806',
      functionCall: true,
      id: 'gpt-4o-2024-08-06',
      releasedAt: '2024-08-06',
      vision: true,
    },
    {
      contextWindowTokens: 128_000,
      description: '',
      displayName: 'GPT-4o 0513',
      functionCall: true,
      id: 'gpt-4o-2024-05-13',
      releasedAt: '2024-05-13',
      vision: true,
    },
    {
      contextWindowTokens: 128_000,
      description:
        'ChatGPT-4o 是一款动态模型，实时更新以保持当前最新版本。它结合了强大的语言理解与生成能力，适合于大规模应用场景，包括客户服务、教育和技术支持。',
      displayName: 'ChatGPT-4o',
      enabled: true,
      id: 'chatgpt-4o-latest',
      vision: true,
    },
    {
      contextWindowTokens: 128_000,
      description: '',
      displayName: 'GPT-4 Turbo',
      functionCall: true,
      id: 'gpt-4-turbo',
      vision: true,
    },
    {
      contextWindowTokens: 128_000,
      description: '',
      displayName: 'GPT-4 Turbo Vision 0409',
      functionCall: true,
      id: 'gpt-4-turbo-2024-04-09',
      vision: true,
    },
    {
      contextWindowTokens: 128_000,
      description: '',
      displayName: 'GPT-4 Turbo Preview',
      functionCall: true,
      id: 'gpt-4-turbo-preview',
    },
    {
      contextWindowTokens: 128_000,
      description: '',
      displayName: 'GPT-4 Turbo Preview 0125',
      functionCall: true,
      id: 'gpt-4-0125-preview',
    },
    {
      contextWindowTokens: 128_000,
      description:
        '最新的 GPT-4 Turbo 模型具备视觉功能。现在，视觉请求可以使用 JSON 模式和函数调用。 GPT-4 Turbo 是一个增强版本，为多模态任务提供成本效益高的支持。它在准确性和效率之间找到平衡，适合需要进行实时交互的应用程序场景。',
      displayName: 'GPT-4 Turbo Preview 1106',
      functionCall: true,
      id: 'gpt-4-1106-preview',
    },
    {
      contextWindowTokens: 8192,
      description: '',
      displayName: 'GPT-4',
      functionCall: true,
      id: 'gpt-4',
    },
    {
      contextWindowTokens: 8192,
      description: '',
      displayName: 'GPT-4 0613',
      functionCall: true,
      id: 'gpt-4-0613',
    },
    {
      contextWindowTokens: 32_768,
      description: '',
      // Will be discontinued on June 6, 2025
      displayName: 'GPT-4 32K',
      functionCall: true,
      id: 'gpt-4-32k',
    },
    {
      contextWindowTokens: 32_768,
      // Will be discontinued on June 6, 2025
      description: '',
      displayName: 'GPT-4 32K 0613',
      functionCall: true,
      id: 'gpt-4-32k-0613',
    },
    {
      contextWindowTokens: 16_385,
      description: '',
      displayName: 'GPT-3.5 Turbo',
      functionCall: true,
      id: 'gpt-3.5-turbo',
    },
    {
      contextWindowTokens: 16_385,
      description: '',
      displayName: 'GPT-3.5 Turbo 0125',
      functionCall: true,
      id: 'gpt-3.5-turbo-0125',
    },
    {
      contextWindowTokens: 16_385,
      description: '',
      displayName: 'GPT-3.5 Turbo 1106',
      functionCall: true,
      id: 'gpt-3.5-turbo-1106',
    },
    {
      contextWindowTokens: 4096,
      description: '',
      displayName: 'GPT-3.5 Turbo Instruct',
      id: 'gpt-3.5-turbo-instruct',
    },
  ],
  checkModel: 'gpt-5-nano',
  description: '',
  enabled: true,
  id: 'openai',
  modelList: { showModelFetcher: true },
  modelsUrl: 'https://platform.openai.com/docs/models',
  name: 'OpenAI',
  settings: {
    responseAnimation: 'smooth',
    showModelFetcher: true,
    supportResponsesApi: true,
  },
  url: 'https://openai.com',
};

export default OpenAI;
