import { ModelProviderCard } from '@/types/llm';

// ref :https://openrouter.ai/docs#models
const OpenRouter: ModelProviderCard = {
  chatModels: [
    {
      contextWindowTokens: 128_000,
      description: '',
      displayName: 'Auto (best for prompt)',
      enabled: true,
      functionCall: false,
      id: 'openrouter/auto',
      vision: false,
    },
    {
      contextWindowTokens: 128_000,
      description: '',
      displayName: 'OpenAI o1-mini',
      enabled: true,
      id: 'openai/o1-mini',
      maxOutput: 65_536,
      releasedAt: '2024-09-12',
    },
    {
      contextWindowTokens: 200_000,
      description: '',
      displayName: 'OpenAI o1',
      enabled: true,
      id: 'openai/o1',
      maxOutput: 100_000,
      releasedAt: '2024-12-17',
      vision: true,
    },
    {
      contextWindowTokens: 128_000,
      description: '',
      displayName: 'OpenAI o1-preview',
      enabled: true,
      id: 'openai/o1-preview',
      maxOutput: 32_768,
      releasedAt: '2024-09-12',
    },
    {
      contextWindowTokens: 128_000,
      description: '',
      displayName: 'GPT-4o mini',
      enabled: true,
      functionCall: true,
      id: 'openai/gpt-4o-mini',
      maxOutput: 16_385,
      vision: true,
    },
    {
      contextWindowTokens: 128_000,
      description: '',
      displayName: 'GPT-4o',
      enabled: true,
      functionCall: true,
      id: 'openai/gpt-4o',
      vision: true,
    },
    {
      contextWindowTokens: 200_000,
      description: '',
      displayName: 'Claude 3 Haiku',
      enabled: true,
      functionCall: true,
      id: 'anthropic/claude-3-haiku',
      maxOutput: 4096,
      releasedAt: '2024-03-07',
      vision: true,
    },
    {
      contextWindowTokens: 200_000,
      description: '',
      displayName: 'Claude 3.5 Haiku',
      enabled: true,
      functionCall: true,
      id: 'anthropic/claude-3.5-haiku',
      maxOutput: 8192,
      releasedAt: '2024-11-05',
    },
    {
      contextWindowTokens: 200_000,
      description: '',
      displayName: 'Claude 3.5 Sonnet',
      enabled: true,
      functionCall: true,
      id: 'anthropic/claude-3.5-sonnet',
      maxOutput: 8192,
      releasedAt: '2024-06-20',
      vision: true,
    },
    {
      contextWindowTokens: 200_000,
      description: '',
      displayName: 'Claude 3 Opus',
      enabled: true,
      functionCall: true,
      id: 'anthropic/claude-3-opus',
      maxOutput: 4096,
      releasedAt: '2024-02-29',
      vision: true,
    },
    {
      contextWindowTokens: 1_000_000 + 8192,
      description: '',
      displayName: 'Gemini 1.5 Flash',
      enabled: true,
      functionCall: true,
      id: 'google/gemini-flash-1.5',
      maxOutput: 8192,
      vision: true,
    },
    {
      contextWindowTokens: 1_048_576 + 8192,
      description: '',
      displayName: 'Gemini 2.0 Flash',
      enabled: true,
      functionCall: true,
      id: 'google/gemini-2.0-flash-001',
      maxOutput: 8192,
      releasedAt: '2025-02-05',
      vision: true,
    },
    {
      contextWindowTokens: 2_000_000 + 8192,
      description: '',
      displayName: 'Gemini 1.5 Pro',
      enabled: true,
      functionCall: true,
      id: 'google/gemini-pro-1.5',
      maxOutput: 8192,
      vision: true,
    },
    {
      contextWindowTokens: 128_000,
      description: '',
      displayName: 'DeepSeek V2.5',
      enabled: true,
      functionCall: true,
      id: 'deepseek/deepseek-chat',
      releasedAt: '2024-09-05',
    },
    {
      contextWindowTokens: 163_840,
      description: '',
      displayName: 'DeepSeek R1',
      enabled: true,
      functionCall: false,
      id: 'deepseek/deepseek-r1',
      releasedAt: '2025-01-20',
    },
    {
      contextWindowTokens: 163_840,
      description: '',
      displayName: 'DeepSeek R1 (Free)',
      enabled: true,
      functionCall: false,
      id: 'deepseek/deepseek-r1:free',
      releasedAt: '2025-01-20',
    },
    {
      contextWindowTokens: 131_072,
      description: '',
      displayName: 'Llama 3.2 11B Vision',
      enabled: true,
      id: 'meta-llama/llama-3.2-11b-vision-instruct',
      vision: true,
    },
    {
      contextWindowTokens: 131_072,
      description: '',
      displayName: 'Llama 3.2 90B Vision',
      enabled: true,
      id: 'meta-llama/llama-3.2-90b-vision-instruct',
      vision: true,
    },
    {
      contextWindowTokens: 32_768,
      description: '',
      displayName: 'Llama 3.3 70B Instruct',
      enabled: true,
      functionCall: true,
      id: 'meta-llama/llama-3.3-70b-instruct',
    },
    {
      contextWindowTokens: 32_768,
      description: '',
      displayName: 'Llama 3.3 70B Instruct (Free)',
      enabled: true,
      functionCall: true,
      id: 'meta-llama/llama-3.3-70b-instruct:free',
    },
    {
      contextWindowTokens: 32_768,
      description: '',
      displayName: 'Qwen2 7B (Free)',
      enabled: true,
      id: 'qwen/qwen-2-7b-instruct:free',
    },
    {
      contextWindowTokens: 32_768,
      description: '',
      displayName: 'Llama 3.1 8B (Free)',
      enabled: true,
      id: 'meta-llama/llama-3.1-8b-instruct:free',
    },
    {
      contextWindowTokens: 8192,
      description: '',
      displayName: 'Gemma 2 9B (Free)',
      enabled: true,
      id: 'google/gemma-2-9b-it:free',
    },
    {
      contextWindowTokens: 2_097_152 + 8192,
      description: '',
      displayName: 'Gemini 2.0 Pro Experimental 02-05 (Free)',
      enabled: true,
      functionCall: true,
      id: 'google/gemini-2.0-pro-exp-02-05:free',
      maxOutput: 8192,
      releasedAt: '2025-02-05',
      vision: true,
    },
  ],
  checkModel: 'google/gemma-2-9b-it:free',
  description: '',
  id: 'openrouter',
  modelList: { showModelFetcher: true },
  modelsUrl: 'https://openrouter.ai/models',
  name: 'OpenRouter',
  settings: {
    // OpenRouter don't support browser request
    // https://github.com/lobehub/lobe-chat/issues/5900
    disableBrowserRequest: true,
    proxyUrl: {
      placeholder: 'https://openrouter.ai/api/v1',
    },
    sdkType: 'openai',
    searchMode: 'params',
    showModelFetcher: true,
  },
  url: 'https://openrouter.ai',
};

export default OpenRouter;
