import { ModelProviderCard } from '@/types/llm';

// ref: https://help.aliyun.com/zh/model-studio/getting-started/models
const Qwen: ModelProviderCard = {
  chatModels: [
    {
      contextWindowTokens: 1_000_000,
      description: '',
      displayName: 'Qwen Turbo',
      enabled: true,
      functionCall: true,
      id: 'qwen-turbo-latest',
    },
    {
      contextWindowTokens: 131_072,
      description: '',
      displayName: 'Qwen Plus',
      enabled: true,
      functionCall: true,
      id: 'qwen-plus-latest',
    },
    {
      contextWindowTokens: 32_768,
      description: '',
      displayName: 'Qwen Max',
      enabled: true,
      functionCall: true,
      id: 'qwen-max-latest',
    },
    {
      contextWindowTokens: 1_000_000,
      description: '',
      displayName: 'Qwen Long',
      id: 'qwen-long',
    },
    {
      contextWindowTokens: 32_000,
      description: '',
      displayName: 'Qwen VL Plus',
      enabled: true,
      id: 'qwen-vl-plus-latest',
      vision: true,
    },
    {
      contextWindowTokens: 32_768,
      description: '',
      displayName: 'Qwen VL Max',
      enabled: true,
      id: 'qwen-vl-max-latest',
      vision: true,
    },
    {
      contextWindowTokens: 34_096,
      description: '',
      displayName: 'Qwen VL OCR',
      id: 'qwen-vl-ocr-latest',
      vision: true,
    },
    {
      contextWindowTokens: 4096,
      description: '',
      displayName: 'Qwen Math Turbo',
      id: 'qwen-math-turbo-latest',
    },
    {
      contextWindowTokens: 4096,
      description: '',
      displayName: 'Qwen Math Plus',
      id: 'qwen-math-plus-latest',
    },
    {
      contextWindowTokens: 131_072,
      description: '',
      displayName: 'Qwen Coder Turbo',
      id: 'qwen-coder-turbo-latest',
    },
    {
      contextWindowTokens: 131_072,
      description: '',
      displayName: 'Qwen Coder Plus',
      id: 'qwen-coder-plus-latest',
    },
    {
      contextWindowTokens: 32_768,
      description: '',
      displayName: 'QwQ 32B Preview',
      id: 'qwq-32b-preview',
    },
    {
      contextWindowTokens: 32_768,
      description: '',
      displayName: 'QVQ 72B Preview',
      id: 'qvq-72b-preview',
      releasedAt: '2024-12-25',
      vision: true,
    },
    {
      contextWindowTokens: 131_072,
      description: '',
      displayName: 'Qwen2.5 7B',
      functionCall: true,
      id: 'qwen2.5-7b-instruct',
    },
    {
      contextWindowTokens: 131_072,
      description: '',
      displayName: 'Qwen2.5 14B',
      functionCall: true,
      id: 'qwen2.5-14b-instruct',
    },
    {
      contextWindowTokens: 131_072,
      description: '',
      displayName: 'Qwen2.5 32B',
      functionCall: true,
      id: 'qwen2.5-32b-instruct',
    },
    {
      contextWindowTokens: 131_072,
      description: '',
      displayName: 'Qwen2.5 72B',
      functionCall: true,
      id: 'qwen2.5-72b-instruct',
    },
    {
      contextWindowTokens: 1_000_000,
      description: '',
      displayName: 'Qwen2.5 14B 1M',
      functionCall: true,
      id: 'qwen2.5-14b-instruct-1m',
    },
    {
      contextWindowTokens: 4096,
      description: '',
      displayName: 'Qwen2.5 Math 7B',
      id: 'qwen2.5-math-7b-instruct',
    },
    {
      contextWindowTokens: 4096,
      description: '',
      displayName: 'Qwen2.5 Math 72B',
      id: 'qwen2.5-math-72b-instruct',
    },
    {
      contextWindowTokens: 131_072,
      description: '',
      displayName: 'Qwen2.5 Coder 7B',
      id: 'qwen2.5-coder-7b-instruct',
    },
    {
      contextWindowTokens: 131_072,
      description: '',
      displayName: 'Qwen2.5 Coder 32B',
      id: 'qwen2.5-coder-32b-instruct',
    },
    {
      contextWindowTokens: 8000,
      description: '',
      displayName: 'Qwen VL',
      id: 'qwen-vl-v1',
      vision: true,
    },
    {
      contextWindowTokens: 8000,
      description: '',
      displayName: 'Qwen VL Chat',
      id: 'qwen-vl-chat-v1',
      vision: true,
    },
    {
      contextWindowTokens: 128_000,
      description: '',
      displayName: 'Qwen2.5 VL 72B',
      id: 'qwen2.5-vl-72b-instruct',
      releasedAt: '2025-01-26',
      vision: true,
    },
    {
      contextWindowTokens: 131_072,
      description: '',
      displayName: 'DeepSeek R1',
      id: 'deepseek-r1',
      releasedAt: '2025-01-27',
    },
    {
      contextWindowTokens: 131_072,
      description: '',
      displayName: 'DeepSeek V3',
      id: 'deepseek-v3',
      releasedAt: '2025-01-27',
    },
    {
      contextWindowTokens: 131_072,
      description: '',
      displayName: 'DeepSeek R1 Distill Qwen 1.5B',
      id: 'deepseek-r1-distill-qwen-1.5b',
      releasedAt: '2025-02-05',
    },
    {
      contextWindowTokens: 131_072,
      description: '',
      displayName: 'DeepSeek R1 Distill Qwen 7B',
      id: 'deepseek-r1-distill-qwen-7b',
      releasedAt: '2025-02-05',
    },
    {
      contextWindowTokens: 131_072,
      description: '',
      displayName: 'DeepSeek R1 Distill Qwen 14B',
      id: 'deepseek-r1-distill-qwen-14b',
      releasedAt: '2025-02-05',
    },
    {
      contextWindowTokens: 131_072,
      description: '',
      displayName: 'DeepSeek R1 Distill Qwen 32B',
      id: 'deepseek-r1-distill-qwen-32b',
      releasedAt: '2025-02-05',
    },
    {
      contextWindowTokens: 131_072,
      description: '',
      displayName: 'DeepSeek R1 Distill Llama 8B',
      id: 'deepseek-r1-distill-llama-8b',
      releasedAt: '2025-02-05',
    },
    {
      contextWindowTokens: 131_072,
      description: '',
      displayName: 'DeepSeek R1 Distill Llama 70B',
      id: 'deepseek-r1-distill-llama-70b',
      releasedAt: '2025-02-05',
    },
  ],
  checkModel: 'qwen-flash',
  description: '',
  disableBrowserRequest: true,
  id: 'qwen',
  modelList: { showModelFetcher: true },
  modelsUrl: 'https://help.aliyun.com/zh/dashscope/developer-reference/api-details',
  name: 'Aliyun Bailian',
  settings: {
    disableBrowserRequest: true,
    proxyUrl: {
      placeholder: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    },
    responseAnimation: {
      speed: 2,
      text: 'smooth',
    },
    sdkType: 'openai',
    showDeployName: true,
    showModelFetcher: true,
  },
  url: 'https://www.aliyun.com/product/bailian',
};

export default Qwen;
