import { ModelProviderCard } from '@/types/llm';

// ref: https://siliconflow.cn/zh-cn/pricing
const SiliconCloud: ModelProviderCard = {
  chatModels: [
    {
      contextWindowTokens: 65_536,
      description: '',
      displayName: 'DeepSeek R1',
      enabled: true,
      id: 'deepseek-ai/DeepSeek-R1',
    },
    {
      contextWindowTokens: 65_536,
      description: '',
      displayName: 'DeepSeek V3',
      enabled: true,
      functionCall: true,
      id: 'deepseek-ai/DeepSeek-V3',
    },
    {
      contextWindowTokens: 65_536,
      description: '',
      displayName: 'DeepSeek R1 (Pro)',
      id: 'Pro/deepseek-ai/DeepSeek-R1',
    },
    {
      contextWindowTokens: 65_536,
      description: '',
      displayName: 'DeepSeek V3 (Pro)',
      functionCall: true,
      id: 'Pro/deepseek-ai/DeepSeek-V3',
    },
    {
      contextWindowTokens: 32_768,
      description: '',
      displayName: 'DeepSeek R1 Distill Llama 70B',
      enabled: true,
      id: 'deepseek-ai/DeepSeek-R1-Distill-Llama-70B',
    },
    {
      contextWindowTokens: 32_768,
      description: '',
      displayName: 'DeepSeek R1 Distill Qwen 32B',
      enabled: true,
      id: 'deepseek-ai/DeepSeek-R1-Distill-Qwen-32B',
    },
    {
      contextWindowTokens: 32_768,
      description: '',
      displayName: 'DeepSeek R1 Distill Qwen 14B',
      enabled: true,
      id: 'deepseek-ai/DeepSeek-R1-Distill-Qwen-14B',
    },
    {
      contextWindowTokens: 32_768,
      description: '',
      displayName: 'DeepSeek R1 Distill Llama 8B (Free)',
      enabled: true,
      id: 'deepseek-ai/DeepSeek-R1-Distill-Llama-8B',
    },
    {
      contextWindowTokens: 32_768,
      description: '',
      displayName: 'DeepSeek R1 Distill Qwen 7B (Free)',
      enabled: true,
      id: 'deepseek-ai/DeepSeek-R1-Distill-Qwen-7B',
    },
    {
      contextWindowTokens: 32_768,
      description: '',
      displayName: 'DeepSeek-R1-Distill-Qwen-1.5B (Free)',
      id: 'deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B',
    },
    {
      contextWindowTokens: 32_768,
      description: '',
      displayName: 'DeepSeek V2.5',
      enabled: true,
      functionCall: true,
      id: 'deepseek-ai/DeepSeek-V2.5',
    },
    {
      contextWindowTokens: 4096,
      description: '',
      displayName: 'DeepSeek VL2',
      id: 'deepseek-ai/deepseek-vl2',
      vision: true,
    },
    {
      contextWindowTokens: 32_768,
      description: '',
      displayName: 'QVQ 72B Preview',
      enabled: true,
      id: 'Qwen/QVQ-72B-Preview',
      vision: true,
    },
    {
      contextWindowTokens: 32_768,
      description: '',
      displayName: 'QwQ 32B Preview',
      enabled: true,
      id: 'Qwen/QwQ-32B-Preview',
    },
    {
      contextWindowTokens: 32_768,
      description: '',
      displayName: 'Qwen2.5 7B Instruct (Free)',
      enabled: true,
      functionCall: true,
      id: 'Qwen/Qwen2.5-7B-Instruct',
    },
    {
      contextWindowTokens: 32_768,
      description: '',
      displayName: 'Qwen2.5 7B Instruct (LoRA)',
      id: 'LoRA/Qwen/Qwen2.5-7B-Instruct',
    },
    {
      contextWindowTokens: 32_768,
      description: '',
      displayName: 'Qwen2.5 7B Instruct (Pro)',
      functionCall: true,
      id: 'Pro/Qwen/Qwen2.5-7B-Instruct',
    },
    {
      contextWindowTokens: 32_768,
      description: '',
      displayName: 'Qwen2.5 14B Instruct',
      functionCall: true,
      id: 'Qwen/Qwen2.5-14B-Instruct',
    },
    {
      contextWindowTokens: 32_768,
      description: '',
      displayName: 'Qwen2.5 32B Instruct',
      functionCall: true,
      id: 'Qwen/Qwen2.5-32B-Instruct',
    },
    {
      contextWindowTokens: 32_768,
      description: '',
      displayName: 'Qwen2.5 72B Instruct',
      functionCall: true,
      id: 'Qwen/Qwen2.5-72B-Instruct',
    },
    {
      contextWindowTokens: 32_768,
      description: '',
      displayName: 'Qwen2.5 72B Instruct (LoRA)',
      id: 'LoRA/Qwen/Qwen2.5-72B-Instruct',
    },
    {
      contextWindowTokens: 32_768,
      description: '',
      displayName: 'Qwen2.5 72B Instruct (Vendor-A)',
      functionCall: true,
      id: 'Vendor-A/Qwen/Qwen2.5-72B-Instruct',
    },
    {
      contextWindowTokens: 131_072,
      description: '',
      displayName: 'Qwen2.5 72B Instruct 128K',
      enabled: true,
      functionCall: true,
      id: 'Qwen/Qwen2.5-72B-Instruct-128K',
    },
    {
      contextWindowTokens: 32_768,
      description: '',
      displayName: 'Qwen2.5 Coder 7B Instruct (Free)',
      id: 'Qwen/Qwen2.5-Coder-7B-Instruct',
    },
    {
      contextWindowTokens: 32_768,
      description: '',
      displayName: 'Qwen2.5 Coder 7B Instruct (Pro)',
      id: 'Pro/Qwen/Qwen2.5-Coder-7B-Instruct',
    },
    {
      contextWindowTokens: 32_768,
      description: '',
      displayName: 'Qwen2.5 Coder 32B Instruct',
      id: 'Qwen/Qwen2.5-Coder-32B-Instruct',
    },
    {
      contextWindowTokens: 32_768,
      description: '',
      displayName: 'Qwen2 1.5B Instruct (Free)',
      id: 'Qwen/Qwen2-1.5B-Instruct',
    },
    {
      contextWindowTokens: 32_768,
      description: '',
      displayName: 'Qwen2 1.5B Instruct (Pro)',
      id: 'Pro/Qwen/Qwen2-1.5B-Instruct',
    },
    {
      contextWindowTokens: 32_768,
      description: '',
      displayName: 'Qwen2 7B Instruct (Free)',
      id: 'Qwen/Qwen2-7B-Instruct',
    },
    {
      contextWindowTokens: 32_768,
      description: '',
      displayName: 'Qwen2 7B Instruct (Pro)',
      id: 'Pro/Qwen/Qwen2-7B-Instruct',
    },
    {
      contextWindowTokens: 32_768,
      description: '',
      displayName: 'Qwen2 72B Instruct',
      id: 'Qwen/Qwen2-7B-Instruct',
    },
    {
      contextWindowTokens: 32_768,
      description: '',
      displayName: 'Qwen2 VL 7B Instruct (Pro)',
      enabled: true,
      id: 'Pro/Qwen/Qwen2-VL-7B-Instruct',
      vision: true,
    },
    {
      contextWindowTokens: 32_768,
      description: '',
      displayName: 'Qwen2 VL 72B Instruct',
      enabled: true,
      id: 'Qwen/Qwen2-VL-72B-Instruct',
      vision: true,
    },
    {
      contextWindowTokens: 32_768,
      description: '',
      displayName: 'InternLM2.5 7B Chat (Free)',
      functionCall: true,
      id: 'internlm/internlm2_5-7b-chat',
    },
    {
      contextWindowTokens: 32_768,
      description: '',
      displayName: 'InternLM2.5 20B Chat',
      functionCall: true,
      id: 'internlm/internlm2_5-20b-chat',
    },
    {
      contextWindowTokens: 32_768,
      description: '',
      displayName: 'InternVL2 8B (Pro)',
      id: 'Pro/OpenGVLab/InternVL2-8B',
      vision: true,
    },
    {
      contextWindowTokens: 32_768,
      description: '',
      displayName: 'InternVL2 26B',
      id: 'OpenGVLab/InternVL2-26B',
      vision: true,
    },
    {
      contextWindowTokens: 131_072,
      description: '',
      displayName: 'GLM-4 9B Chat (Free)',
      functionCall: true,
      id: 'THUDM/glm-4-9b-chat',
    },
    {
      contextWindowTokens: 131_072,
      description: '',
      displayName: 'GLM-4 9B Chat (Pro)',
      functionCall: true,
      id: 'Pro/THUDM/glm-4-9b-chat',
    },
    {
      contextWindowTokens: 32_768,
      description: '',
      displayName: 'ChatGLM3 6B (Free)',
      id: 'THUDM/chatglm3-6b',
    },
    {
      contextWindowTokens: 4096,
      description: '',
      displayName: 'Yi-1.5 6B Chat (Free)',
      id: '01-ai/Yi-1.5-6B-Chat',
    },
    {
      contextWindowTokens: 16_384,
      description: '',
      displayName: 'Yi-1.5 9B Chat 16K (Free)',
      id: '01-ai/Yi-1.5-9B-Chat-16K',
    },
    {
      contextWindowTokens: 16_384,
      description: '',
      displayName: 'Yi-1.5 34B Chat 16K',
      id: '01-ai/Yi-1.5-34B-Chat-16K',
    },
    {
      contextWindowTokens: 8192,
      description: '',
      displayName: 'Gemma 2 9B (Free)',
      enabled: true,
      id: 'google/gemma-2-9b-it',
    },
    {
      contextWindowTokens: 8192,
      description: '',
      displayName: 'Gemma 2 9B (Pro)',
      id: 'Pro/google/gemma-2-9b-it',
    },
    {
      contextWindowTokens: 8192,
      description: '',
      displayName: 'Gemma 2 27B',
      enabled: true,
      id: 'google/gemma-2-27b-it',
    },
    {
      contextWindowTokens: 32_768,
      description: '',
      displayName: 'Llama 3.1 8B Instruct (Free)',
      enabled: true,
      functionCall: true,
      id: 'meta-llama/Meta-Llama-3.1-8B-Instruct',
    },
    {
      contextWindowTokens: 32_768,
      description: '',
      displayName: 'Llama 3.1 8B Instruct (Pro)',
      id: 'Pro/meta-llama/Meta-Llama-3.1-8B-Instruct',
    },
    {
      contextWindowTokens: 32_768,
      description: '',
      displayName: 'Llama 3.1 70B Instruct',
      enabled: true,
      functionCall: true,
      id: 'meta-llama/Meta-Llama-3.1-70B-Instruct',
    },
    {
      contextWindowTokens: 32_768,
      description: '',
      displayName: 'Llama 3.1 405B Instruct',
      enabled: true,
      id: 'meta-llama/Meta-Llama-3.1-405B-Instruct',
    },
    {
      contextWindowTokens: 32_768,
      description: '',
      displayName: 'Llama 3.3 70B Instruct',
      enabled: true,
      functionCall: true,
      id: 'meta-llama/Llama-3.3-70B-Instruct',
    },
    {
      contextWindowTokens: 8192,
      description: '',
      displayName: 'TeleChat2',
      id: 'TeleAI/TeleChat2',
    },
    {
      contextWindowTokens: 32_768,
      description: '',
      displayName: 'TeleMM',
      id: 'TeleAI/TeleMM',
      vision: true,
    },
  ],
  checkModel: 'Pro/Qwen/Qwen2-7B-Instruct',
  description: '',
  id: 'siliconcloud',
  modelList: { showModelFetcher: true },
  modelsUrl: 'https://siliconflow.cn/zh-cn/models',
  name: 'SiliconCloud',
  settings: {
    proxyUrl: {
      placeholder: 'https://api.siliconflow.cn/v1',
    },
    sdkType: 'openai',
    showModelFetcher: true,
  },
  url: 'https://siliconflow.cn/zh-cn/siliconcloud',
};

export default SiliconCloud;
